services:
  - type: web
    name: civicpulse-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: APP_NAME
        value: CivicPulse
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: PORT
        value: "8000"
      - key: CORS_ORIGINS
        value: "*"
      - key: NEXT_PUBLIC_APP_URL
        value: "https://celadon-sfogliatella-937900.netlify.app"
      - key: GROQ_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "30"
      - key: SUPABASE_STORAGE_BUCKET
        value: tickets
    healthCheckPath: /health
    autoDeploy: true